#!/bin/bash
echo "For user creation press u and for user deletion press d:"
read u
if [ "$u" == "u" ]
then
echo "Enter the user name to create with home directory with admin privilege:"
read a
sudo sysadminctl -addUser demo -fullName “$a” -password Welcome@123 -home /Users/$a -admin
else
        echo "Enter the user name to delete on this machine:"
        read d
fi

id demo
dscl . list /Users
sudo dscl . -delete /Users/test
sudo dscl . -delete /Groups/groupname GroupMembership username
# Directory Service command line utility
. Represent Essentially, you're telling dscl to work with the local user database on your machine.
chmod +x myscript.sh.
